sudo: required
language: bash
env:
  global:
  - BUILD_NAME=2D-rpg
  - secure: RcbpPRhQ3ik7qMPXQ6QWNNB5pb8pAKY/agrw3BiyvvPI39vnfi0RmC5CUzzmu7vHv0ueLdyNa2OBdonTr/1j98TaTeS9ifS8+Emd3aoG+mNRcjlbMHIirE44UshJF00wJnjw4zKRLbP7wJeZ2IRfbTm5ZLGwDMY3b4YrAUkM0A9NPSZjMFqW2/n4eGP+35/jEkX9/olgVhTNstnVp0zANkVgLHeemFJ5/7erXgnCFkjLyBkDBlrBtPjj+vPJK454ublFSfQ7ggYU5LyvkiYTWFO63P0JKLAtLJoYNVUkN/K6f1bN8Xs4F8jTbUZsOjou8sIJq8se8di90B6xM6YZIcA06a3hGaTAxkWrKOJyIuwZdTCcwtd/OkOTZsx6+xPnC/1noK0oJB8l4MJJ82IX3O9ImPyPjGxeRXQtxJk/qbo6k7lAd9UhceT2f7UQTeykVuzDI0dxF4TRtoJGw7+Dbiwe4mpaWHgs0ac08Z7n/mCzYzHo4XEICHnXLGfEYDqtuovZ/SQyLL4VxdDhC9b7fhgHbEKqA+wzRR/iVh+2hdByHgpO23sq9fl3pI6Z/ze8zy8qnoxOPwSQ84BitkbtwNdhApb76JWM/Z9506BN+6HzVIpaQxiIg9TojOiqIo6mTruf+zK4yigI8SlS0WPZF8Cv0+iPO1SrmfESxVwdz38=
  - secure: h9vKw5ywxoQXks3NFcGxk/Bo7Sd8zqGyq21Vu8w9nRPuo+YHaTeKn8aQN1WYaaEKoxGW8qPu87m408i6Jf9Y6qqu9CVO7YIHXfmu/C8qOicQpiIVjTlD5wDjkcLXf7B2vSY6ZFBAehMfx+YEMNoiheVPwcu/BFoREeMfRaYP82GqX/51ZKWAuZuKT+qKfvbbxE1UnjbKuw/n9lbozoZeoeJiAQopY/BTAmk3BpsVHEhTNsVFaWMxfm21wBgoU3F3WWVCgvJLyMHMPdfAgZdEwU5XnWxTdBHDIqFultbfTy/ip6Pr+Jze1EZQGEDMMGVm07n9oF7m8ods7KHx+5DAtVQJ1cmafq6lMNmaZbyYG4mqLWBKZP5GE4zWmHNo/tHgJ19hGFvbhDkrWFycksMeT4xjpb+Bbfxh8wWCQeHql6d4qUv1B5AkBnXXFhFanmPZ+FcKXHy+rvW3m8OLEGgBnZd4CRMDnJES1fWoN0drZJK4Q6U+WvbmJ3dzSL/BksQVZESwhrEHs14kBiM4n2wGCc4tMICNbJ4BldvRevEYAo0zZpvvHs1Oh8HvtniNGqbgdPXTXVePiuHWG1fvI0nN8dRaJWS511keoSdS4zPVZM9fajetSPpCtLLC5V8XW7GDwWEjtQtKF9ugCkGNJh6HwEIPcUCUuGCkDkbGZUyrWK8=
services:
- docker
before_install:
- openssl aes-256-cbc -K $encrypted_ce143bb546cb_key -iv $encrypted_ce143bb546cb_iv
  -in Unity_v2019.x.ulf.enc -out ./Unity_v2019.x.ulf -d
- export UNITY_LICENSE_CONTENT=`cat Unity_v2019.x.ulf`
- echo ${UNITY_LICENSE_CONTENT}
- docker pull $IMAGE_NAME
jobs:
  include:
  - stage: build
    env: BUILD_TARGET=StandaloneLinux64 IMAGE_NAME=gableroux/unity3d:2019.4.1f1
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: eu-west-1
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=StandaloneOSX IMAGE_NAME=gableroux/unity3d:2019.4.1f1-mac
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: eu-west-1
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=StandaloneWindows64 IMAGE_NAME=gableroux/unity3d:2019.4.1f1-windows
    script: chmod +x ./ci/docker_build.sh &&./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: eu-west-1
        paths:
        - "./Builds/"
  - stage: build
    env: BUILD_TARGET=WebGL IMAGE_NAME=gableroux/unity3d:2019.4.1f1-webgl
    script: chmod +x ./ci/docker_build.sh && ./ci/docker_build.sh
    addons:
      artifacts:
        s3_region: eu-west-1
        paths:
        - "./Builds/"
